name = "quiz-app"
compatibility_date = "2024-08-29"
compatibility_flags = [ "nodejs_compat" ]

[build]
  command = "npm run build:cf"
  publish = ".vercel/static"

[build.upload]
  format = "directory"
  dir = ".vercel/static"

# Required for Next.js API routes
[functions]
  node_compat = true